# Generated by Django 5.1.1 on 2024-11-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collec_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collec',
            old_name='created_at',
            new_name='date',
        ),
    ]
