# Generated by Django 5.1.1 on 2024-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec_management', '0002_rename_created_at_collec_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collec',
            name='date',
            field=models.DateField(),
        ),
    ]
